---
title: "Module8"
author: "Natalie Robinson"
date: "September 25, 2017"
output: html_document
---

#Notes:
* Probabilities summarize the relative frequencies of possible outcomes.
* Probabilities are properties of distributions
* Random variables can be discrete or continuous 
* PMFs associated with discrete RVs
* PDFs (f(x)) associated with continuous RVs
* CDF (F(x)) regardless of whether X is discrete or continuous
* For cont: PDF is the first derivative of the CDF

* Beta Distirbution with pbeta()

* The Bernoulli Distribution is the probability distribution of a binary random variable

* The binomial distribution is typically used to model the probability of a number of “successes” k out of a set of “trials” n, i.e., for counts of a particular outcome 
dbinom() for PDF, pbinom for CDF

* The Poisson Distribution is often used to model open ended counts of independently occuring events (mean and variance are the same); ppois() for CDF

* The Uniform Distribution is the simplest probability density function describing a continuous random variable.

* The Normal or Gaussian Distribution is perhaps the most familiar and most commonly applied probability density functions for modeling continuous random variables; dnorm(), pnorm(), rnorm()

* A quantile-quantile or “Q-Q” plot can be used to look at whether a set of data seem to follow a normal distribution. A Q–Q plot is a graphical method for generally comparing two probability distributions

* Any normal distribution with mean μμ and standard deviation σσ can be converted into what is called the standard normal distribution, where the mean is zero and the standard deviation is 1. (Subtract the mean from all observations and dividing these differences by the standard deviation)

* The standard error of the mean is an estimate of how far a given sample mean is likely to be from the population mean; it is a measure of uncertainty. 
* The standard deviation of a sample is a measure of the degree to which individuals values within a sample differ from the sample mean.

# Homework Problem:
Every Saturday, at the same time, a primatologist goes and sits in the forest in the morning and listens for titi monkey calls, counting the number of calls they hear in a 2 hour window from 5am to 7am. Based on previous knowledge, she believes that the mean number calls she will hear in that time is exactly 15. Let XX represent the appropriate Poisson random variable of the number of calls heard in each monitoring session.

What is the probability that she will hear more than 8 calls during any given session?
What is the probability that she will hear no calls in a session?
What is the probability that she will hear exactly 3 calls in a session?
Plot the relevant Poisson mass function over the values in range 0 ≤ xx ≤ 30.
Simulate 104 results from this distribution (i.e., 2 years of Saturday monitoring sessions).
Plot the simulated results using hist() and use xlim() to set the horizontal limits to be from 0 to 30. How does your histogram compare to the shape of the probability mass function you plotted above?